# Default values for arm64-dockerbuild.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jkaldon/arm64v8-dockerbuild
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "alpine3.15-3"
  command:
    - "/bin/sh"
  args:
    - "-c"
    - "/usr/bin/screen -h 5000 -d -m -l -s /bin/bash && cat"
  env:
    - name: "IGNOREEOF"
      value: "10"
    - name: "PS1"
      value: '\h:\W\$ '
  resources:
    requests:
      memory: 6Gi
      cpu: 2000m

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim:
  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: nfs-client
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  mounts:
    - name: projects-nfs
      mountPath: /root/Projects
  volumes:
    - name: projects-nfs
      nfs: 
        # URL for the NFS server
        server: 192.168.1.2
        path: /nfs/Projects

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80


